### ISSUE TITLE
package.json start script is being ignored

### ISSUE THREAD

**Issue by cesarvarela** [Azure-App-Service/kudu#20]
Changing the start script to `node dist/index.js` and placing a `index.js` file there, even though the log after a push shows this:

```
remote: Using start-up script dist/index.js from package.json.
```

I get a a `502` error. 

If I place a `index.js` file in the root folder of my app, it does work.

**Comment by naziml** [comment]
You need to just remove the starting 'node' in your start script. If we detect you are setting a start script (as opposed to a PM2 process config) we will prepend node for you. More info on https://github.com/Azure-App-Service/node/issues/10
HTH.

**Comment by lostintangent** [comment]
@nickwalkmsft Can this issue be closed now thanks to the updates you made to the Node images?

**Comment by nickwalkmsft** [comment]
Yes, I will close this, but I'm still tracking it as we haven't deployed it yet. I believe our next deployment should include these enhancements.
