### ISSUE TITLE
Composer support?

### ISSUE THREAD

**Issue by cderue** [Azure-App-Service/kudu#6]
It seems that the Kudu image doesn’t include PHP and common tools such as Composer.
Because of this, deployment of PHP applications needing to run composer to get their dependencies (Symfony, Laravel, …) is not possible.

**Comment by michimune** [comment]
Hello, I have added PHP5.6/7.0 and Composer to the Kudu image. It will go to production in our next deployment pipeline. When it becomes available, you can execute composer install in your Kudu window.

We are also going to make changes to KuduScript so Composer will automatically run if composer.json is found.
