### ISSUE TITLE
Kudu docker container needs to be updated to use Node version 6.9.3

### ISSUE THREAD

**Issue by nicolehaugen79** [Azure-App-Service/kudu#9]
The current Kudu docker container doesn't support using Node version 6.9.3.  As a result, the scenario in this walk-through doesn't work as stated in the instructions - specifically, step 5 where it states to 
configure version 6.9.3 to be deployed.

Refer to the following email for details. [NodeVersionIssue.pdf](https://github.com/Azure-App-Service/kudu/files/855307/NodeVersionIssue.pdf)

**Comment by nickwalkmsft** [comment]
Walkthrough/step referenced is [here](https://docs.microsoft.com/en-us/azure/app-service-web/app-service-web-get-started-nodejs#configure-the-linux-container).

This *is* an issue, as 6.9.3 is not installed in the Kudu container on Linux, but this walkthrough as written is confusing, as it walks the user through creating and deploying to a *Windows* App Service, not Linux, and there is no Linux container involved.

**Comment by cephalin** [comment]
The walkthrough is supposed to use the Linux container and was in error. I've created a new PR to remedy it. Thanks again for catching.

**Comment by lostintangent** [comment]
@nickwalkmsft @naziml Let me know how #10 looks, regarding fixing this issue.

**Comment by nickwalkmsft** [comment]
See [here](https://github.com/projectkudu/kudu/issues/2372) for additional details/stack trace.
